- id: validate-legend-chmaps
  name: check LEGEND channel maps format
  entry: validate-legend-chmaps
  language: python
  types: [json]

- id: validate-legend-detdb
  name: check LEGEND detector database format
  entry: validate-legend-detdb
  language: python
  types: [json]
